web:
  build: .
  command: bundle exec rails server -b 0.0.0.0
  ports:
    - "3000:3000"
  volumes:
    - .:/app
  links:
    - database
  environment:
    RACK_ENV: development
    DATABASE_URL: postgres://sehrgutachten:@database/sehrgutachten

database:
  image: postgres:9.4
  environment:
    POSTGRES_USER: sehrgutachten
  ports:
    - 5432
